name: autoupdater
on: push
jobs:
  autoupdater:
    runs-on: ubuntu-latest
    name: autoupdater
    steps:
      - uses: actions/checkout@v2
      - name: Update Pull Requests
        uses: ./
        env:
          GITHUB_TOKEN: "${{ secrets.AUTOUPDATER_TOKEN }}"
