on: push
jobs:
  autoupdater:
    runs-on: ubuntu-latest
    name: updater
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: autoupdate
        uses: ./
        env:
          GITHUB_TOKEN: "${{ secrets.AUTOUPDATER_TOKEN }}"
